# Generated by Django 6.0.5 on 2026-06-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
