# Generated by Django 6.0.5 on 2026-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=100)),
                ('proddes', models.CharField(max_length=100)),
                ('prodprc', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
