# Generated by Django 6.0.5 on 2026-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_department', models.CharField(max_length=25)),
            ],
        ),
    ]
