# Generated by Django 6.0.5 on 2026-06-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
