# Generated by Django 6.0.5 on 2026-06-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=100)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
