# Generated by Django 6.0.5 on 2026-06-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemail',
            name='employeename',
            field=models.CharField(default='Employee', max_length=50),
        ),
    ]
