# Generated by Django 6.0.5 on 2026-06-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_employeemail_employeename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemail',
            name='sent_on',
        ),
    ]
